/* eslint-disable unusedImports/no-unused-vars */
export enum callbackEnum {
  EDIT_NOTE_ = 'EDIT_NOTE_', //EDIT_NOTE_{messageId}
  CANCEL_EDIT_NOTE = 'CANCEL_EDIT_NOTE',

  FOLDER_NOTE_ = 'FOLDER_NOTE_', //FOLDER_NOTE_{messageId}
  CANCEL_FOLDER_NOTE = 'CANCEL_FOLDER_NOTE',

  FOLDER_MENU_ = 'FOLDER_MENU_', //FOLDER_MENU_{folderId}
  CANCEL_FOLDER_MENU_ = 'FOLDER_MENU_', //FOLDER_MENU_{folderId}
  FOLDER_CREATE = 'FOLDER_CREATE',

  ADD_NOTE_TO_FOLDER_ = 'ADD_NOTE_TO_FOLDER_', //ADD_NOTE_TO_FOLDER_{folderId}

  NEW_REMINDER_ = 'NEW_REMINDER_', //NEW_REMINDER_{messageId}
  CANCEL_NEW_REMINDER = 'CANCEL_NEW_REMINDER',
  ENTER_REMINDER_DATE = 'ENTER_REMINDER_DATE',
  CREATE_REMINDER = 'CREATE_REMINDER',

  CONFIRM_NOTIFICATION_ = 'CONFIRM_NOTIFICATION_', //CONFIRM_NOTIFICATION_{reminderId}

  TRASH_NOTE_ = 'TRASH_NOTE_', //TRASH_NOTE_{messageId}
  CANCEL_TRASH_NOTE = 'CANCEL_TRASH_NOTE',
}
